// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGjatpWq_HsTI5-6kgBZ08Y1-zH_ZdeAQ',
    appId: '1:170775739646:web:4550863d6c38afe4b1b9af',
    messagingSenderId: '170775739646',
    projectId: 'addis-chat-app-v1',
    authDomain: 'addis-chat-app-v1.firebaseapp.com',
    storageBucket: 'addis-chat-app-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_MfsdK1-yXTcOGAD9d-AQVPcZBYOf5g',
    appId: '1:170775739646:android:f581c47a0f251f78b1b9af',
    messagingSenderId: '170775739646',
    projectId: 'addis-chat-app-v1',
    storageBucket: 'addis-chat-app-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvVcdYY3LCfF6JAm5fXz5LyFuIS8YpUpI',
    appId: '1:170775739646:ios:d97ae724ea5b9e9fb1b9af',
    messagingSenderId: '170775739646',
    projectId: 'addis-chat-app-v1',
    storageBucket: 'addis-chat-app-v1.firebasestorage.app',
    iosBundleId: 'com.addiscodr.shoppers',
  );
}
